//-----------Load Outs-----------//

_allLoadOuts = [

//-----Autorifleman-----//
["Autorifleman",[["Aux187_DC15L","","acc_flashlight","aux187_optic_15ascope",["aux187_mag_75Rnd_DC15L",75],[],"3AS_bipod_DC15L_F"],[],["aux187_DC17","","","",["aux187_mag_80Rnd_Pistol",80],[],""],["aux187_P2_Base_Uniform",[["ACE_CableTie",3],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["ACE_tourniquet",3],["ACE_bodyBag",1],["ACE_IR_Strobe_Item",2],["ACE_splint",1],["ACE_elasticBandage",20],["IDA_BactaBandage",1],["ACE_EntrenchingTool",1],["kat_guedel",1],["kat_IV_16",1],["ACE_plasmaIV_500",1],["ACE_morphine",2],["ACE_epinephrine",1],["kat_chestSeal",1],["ItemAndroid",1],["ACE_Canteen",2],["ACE_MRE_BeefStew",2],["ACE_MRE_ChickenHerbDumplings",2],["Aux187_mag_80Rnd_Pistol",2,80],["IDA_grenade_Smoke_mag",5,1]]],["aux187_Vest_holster",[["aux187_mag_75Rnd_DC15L",5,75],["IDA_grenade_Detonator_mag",4,1]]],["aux187_backpack_ammo_base",[["aux187_SignalFlare_Green",1,1],["aux187_SignalFlare_Yellow",1,1],["aux187_SignalFlare_Blue",1,1],["aux187_mag_75Rnd_DC15L",8,75]]],"aux187_P2_Base_Helmet","",["IDA_Electrobinoculars_Rep","","","",["Laserbatteries",1],[],""],["ItemMap","","JLTS_clone_comlink","ItemCompass","ACE_Altimeter","Aux187_NVG_Chip"]]],

//-----Breacher DP-23-----//
["Breacher",[["Aux187_DP23","","","",["3AS_10Rnd_EC30_Pellets",10],["3AS_1Rnd_EC80_Flechette",1],""],[],["aux187_DC17","","","",["aux187_mag_80Rnd_pistol", 40],[],""],["aux187_P2_Base_Uniform",[["ACE_CableTie",3],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["ACE_tourniquet",3],["ACE_IR_Strobe_Item",2],["ACE_splint",1],["ACE_elasticBandage",20],["IDA_BactaBandage",1],["ACE_EntrenchingTool",1],["ACE_bodyBag",1],["kat_IV_16",1],["kat_guedel",1],["ACE_plasmaIV_500",1],["ACE_morphine",2],["ACE_epinephrine",1],["kat_chestSeal",1],["ItemAndroid",1],["ACE_MRE_ChickenHerbDumplings",1],["ACE_MRE_BeefStew",1],["ACE_Canteen",1],["aux187_mag_80Rnd_DC17",2,80],["aux187_SignalFlare_Yellow",1,1],["aux187_SignalFlare_Green",1,1],["aux187_SignalFlare_Blue",1,1],["IDA_grenade_Smoke_mag",5,1]]],["aux187_vest_grenade",[["3AS_10Rnd_EC30_Pellets",8,10],["IDA_grenade_Detonator_mag",4,1]]],["aux187_backpack_trooper_base",[["ShieldGrenade_Mag",5,1],["3AS_SonicDet",5,1],["3AS_1Rnd_EC80_Flechette",5,1]]],"aux187_P2_Base_Helmet","3AS_G_Engineer_4_F",["IDA_Electrobinoculars_Rep","","","",["Laserbatteries",1],[],""],["ItemMap","","JLTS_clone_comlink","ItemCompass","ACE_Altimeter","Aux187_NVG_Chip"]]],

//-----Corpsman-----//
["Corpsman",[["Aux187_3as_DC15S","","acc_pointer_IR","",["187th_80RND_15S_Mag",80],[],""],[],["aux187_DC17","","","",["aux187_mag_80Rnd_pistol", 40],[],""],["187th_Clone_Medic",[["ACE_CableTie",3],["ACE_EntrenchingTool",1],["ItemcTabHCam",1],["ACE_IR_Strobe_Item",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_elasticBandage",20],["ACE_plasmaIV_500",1],["ACE_morphine",2],["ACE_epinephrine",1],["kat_chestSeal",1],["kat_guedel",1],["kat_IV_16",1],["IDA_BactaBandage",1],["ACE_splint",1],["ItemAndroid",1],["ACE_tourniquet",3],["ACE_MRE_BeefStew",2],["ACE_Canteen",2],["ACE_MRE_CreamChickenSoup",2],["SquadShieldMagazine",1,1],["IDA_grenade_Smoke_mag",5,1]]],["aux187_vest_grenade",[["187th_80RND_15S_Mag",10,80],["IDA_grenade_Penetrator_mag",1,1],["IDA_grenade_Detonator_mag",2,1]]],["ls_mandalorianBackpack_medic",[["kat_IV_16",2],["kat_accuvac",1],["kat_X_AED",1],["kat_IO_FAST",5],["kat_BVM",1],["kat_chestSeal",4],["ACE_adenosine",2],["kat_atropine",2],["kat_naloxone",2],["kat_fluidWarmer",1],["kat_guedel",1],["kat_larynx",2],["ACE_epinephrine",2],["kat_epinephrineIV",4],["ACE_morphine",2],["kat_fentanyl",2],["ACE_plasmaIV_500",6],["ACE_plasmaIV_250",8],["ACE_plasmaIV",4],["kat_Pulseoximeter",1],["kat_BPCuff",1],["ACE_salineIV_500",4],["ACE_splint",3],["kat_stethoscope",1],["ACE_surgicalKit",1],["442_BactaBandage",9],["kat_nasal",1],["ACE_elasticBandage",40],["kat_oxygenTank_150",1,100],["aux187_SignalFlare_Purple",1,1]]],"aux187_P2_Base_Helmet","187th_Vest_Medic1",["IDA_Electrobinoculars_Rep","","","",["Laserbatteries",1],[],""],["ItemMap","","JLTS_clone_comlink","ItemCompass","ACE_Altimeter","Aux187_NVG_Chip"]]],

//-----Designated Marksman Valken 38X-----//
["Designated Marksman",[["Aux187_3AS_38X","","","3AS_optic_VK38X_F",["187th_15RND_38X_Mag",15],[],"3AS_bipod_VK38X_F"],[],["aux187_DC17","","","",["aux187_mag_80Rnd_pistol", 40],["JLTS_stun_mag_long",5],""],["aux187_P2_Base_Uniform",[["ACE_CableTie",3],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["ACE_tourniquet",3],["ACE_EntrenchingTool",1],["ACE_bodyBag",1],["ACE_IR_Strobe_Item",2],["ACE_splint",1],["ACE_elasticBandage",20],["IDA_BactaBandage",1],["kat_IV_16",1],["kat_guedel",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_plasmaIV_500",1],["kat_chestSeal",1],["ItemAndroid",1],["ACE_Canteen",2],["ACE_MRE_BeefStew",2],["ACE_MRE_ChickenHerbDumplings",2],["aux187_DC17_mag",4,40],["JLTS_stun_mag_long",2,5],["IDA_grenade_Smoke_mag",5,1]]],["aux187_Vest_holster",[["187th_15RND_38X_Mag",5,15],["IDA_grenade_Penetrator_mag",1,1],["IDA_grenade_Detonator_mag",2,1]]],["ls_imperialBackpack_chestRigPouch",[["ACE_SpottingScope",1],["ACE_RangeCard",1],["ACE_Tripod",1],["187th_15RND_38X_Mag",5,15],["Aux187_DC15X_charge_mag",5,1]]],"187_Clone_Helmet","187th_Suspenders",["IDA_Electrobinoculars_Rep","","","",["Laserbatteries",1],[],""],["ItemMap","","JLTS_clone_comlink","ItemCompass","ACE_Altimeter","Aux187_NVG_Chip"]]],

//-----Explosives Specialist-----//
["Sapper",[["Aux187_3as_DC15S","","","",["187th_80RND_15S_Mag",80],[],""],[],["aux187_DC17","","","",["aux187_mag_80Rnd_pistol", 40],["JLTS_stun_mag_long",5],""],["187th_Clone_EOD",[["ACE_CableTie",3],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["ACE_tourniquet",3],["ACE_IR_Strobe_Item",2],["ACE_splint",1],["ACE_elasticBandage",20],["IDA_BactaBandage",1],["ACE_bodyBag",1],["kat_IV_16",1],["kat_guedel",1],["ACE_plasmaIV_500",1],["ACE_epinephrine",1],["ACE_morphine",2],["kat_chestSeal",1],["ACE_DefusalKit",1],["ACE_EntrenchingTool",1],["ItemAndroid",1],["ACE_MRE_BeefStew",1],["ACE_MRE_ChickenHerbDumplings",1],["ACE_Canteen",1],["ACE_M26_Clacker",1],["WBK_HeadLampItem_Narrow",1],["aux187_DC17_mag",4,40],["JLTS_stun_mag_long",2,5],["IDA_grenade_Smoke_mag",5,1]]],["aux187_vest_grenade",[["MineDetector",1],["187th_80RND_15S_Mag",6,80],["IDA_grenade_Penetrator_mag",1,1],["IDA_grenade_Detonator_mag",2,1]]],["Aux187_IDA_Patrol_Pack",[["ItemcTabHCam",1],["ACE_SpraypaintGreen",1],["ACE_SpraypaintRed",1],["aux187_SignalFlare_Yellow",1,1],["aux187_SignalFlare_Green",1,1],["aux187_SignalFlare_Blue",1,1],["187th_80RND_15S_Mag",4,80],["SatchelCharge_Remote_Mag",1,1],["ls_explosive_demoCharge_magazine",2,1],["APERSMineDispenser_Mag",1,1]]],"187_Clone_Helmet","ls_imperial_chestRigPouch",["IDA_Electrobinoculars_Rep","","","",["Laserbatteries",1],[],""],["ItemMap","","JLTS_clone_comlink","ItemCompass","ACE_Altimeter","Aux187_NVG_Chip"]]],

//-----Grenadier DC15S-----//
["Grenadier",[["Aux187_3as_ugl","","","",["187th_80RND_15S_Mag",80],["187th_HE_Grenade_Shell",3],""],[],["aux187_DC17","","","",["aux187_mag_80Rnd_pistol", 40],["JLTS_stun_mag_long",5],""],["aux187_P2_Base_Uniform",[["ACE_CableTie",3],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["ACE_tourniquet",3],["ACE_EntrenchingTool",1],["ACE_bodyBag",1],["ACE_IR_Strobe_Item",2],["ACE_HuntIR_monitor",1],["ACE_splint",1],["IDA_BactaBandage",1],["ACE_elasticBandage",20],["kat_IV_16",1],["kat_guedel",1],["ACE_plasmaIV_500",1],["ACE_morphine",2],["ACE_epinephrine",1],["kat_chestSeal",1],["ItemAndroid",1],["ACE_Canteen",2],["ACE_MRE_BeefStew",1],["ACE_MRE_ChickenHerbDumplings",1],["aux187_DC17_mag",3,40],["JLTS_stun_mag_long",1,5],["IDA_grenade_Smoke_mag",5,1]]],["aux187_vest_grenade",[["187th_80RND_15S_Mag",6,80],["IDA_grenade_Penetrator_mag",1,1],["IDA_grenade_Detonator_mag",4,1]]],["Aux187_IDA_Patrol_Pack",[["aux187_SignalFlare_Blue",1,1],["aux187_SignalFlare_Green",1,1],["aux187_SignalFlare_Yellow",1,1],["aux187_SignalFlare_Red",1,1],["ACE_HuntIR_M203",4,1],["ACE_40mm_Flare_white",4,1],["UGL_FlareGreen_F",2,1],["UGL_FlareRed_F",2,1],["187th_HE_Grenade_Shell",5,3],["187th_AP_Grenade_Shell",3,2],["1Rnd_Smoke_Grenade_shell",5,1],["1Rnd_SmokeRed_Grenade_shell",3,1],["187th_80RND_15S_Mag",4,80]]],"187_Clone_Helmet","ls_imperial_satchelOthers",["IDA_Electrobinoculars_Rep","","","",["Laserbatteries",1],[],""],["ItemMap","","JLTS_clone_comlink","ItemCompass","ACE_Altimeter","Aux187_NVG_Chip"]]],

//-----Heavy AT-----//
["Heavy AT",[["Aux187_3as_DC15S","","","",["187th_80RND_15S_Mag",80],[],""],["Aux187_PLX1","","","",["JLTS_PLX1_AT_mag",2],[],""],["aux187_DC17","","","",["aux187_mag_80Rnd_pistol", 40],["JLTS_stun_mag_long",5],""],["aux187_P2_Base_Uniform",[["ACE_CableTie",3],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["ACE_tourniquet",3],["ACE_EarPlugs",1],["ACE_IR_Strobe_Item",2],["ACE_splint",1],["ACE_elasticBandage",20],["IDA_BactaBandage",1],["kat_guedel",1],["kat_IV_16",1],["ACE_plasmaIV_500",1],["ACE_morphine",2],["ACE_epinephrine",1],["kat_chestSeal",1],["ItemAndroid",1],["WBK_HeadLampItem_Narrow",1],["ACE_EntrenchingTool",1],["ACE_Canteen",2],["ACE_MRE_BeefStew",2],["ACE_MRE_ChickenHerbDumplings",2],["aux187_DC17_mag",4,40],["JLTS_stun_mag_long",2,5],["IDA_grenade_Smoke_mag",5,1]]],["aux187_vest_grenade",[["187th_80RND_15S_Mag",6,80],["IDA_grenade_Penetrator_mag",1,1],["IDA_grenade_Detonator_mag",4,1]]],["3AS_B_CloneTrooper_Rocket_F",[["ACE_bodyBag",1],["aux187_SignalFlare_Blue",1,1],["aux187_SignalFlare_Green",1,1],["aux187_SignalFlare_Yellow",1,1],["JLTS_PLX1_AT_mag",1,2],["JLTS_PLX1_AP_mag",2,2],["187th_80RND_15S_Mag",4,80]]],"aux187_P2_Base_Helmet","ls_imperial_chestRig",["ACE_Vector","","","",[],[],""],["ItemMap","","JLTS_clone_comlink","ItemCompass","ACE_Altimeter","Aux187_NVG_Chip"]]],

//-----Light AT-----//
["Light AT",[["Aux187_3as_DC15S","","","",["187th_80RND_15S_Mag",80],[],""],["Aux187_RPS6","","","",["JLTS_RPS6_mag",1],[],""],["aux187_DC17","","","",["aux187_mag_80Rnd_pistol", 40],["JLTS_stun_mag_long",5],""],["aux187_P2_Base_Uniform",[["ACE_CableTie",3],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["ACE_tourniquet",3],["ACE_EarPlugs",1],["ACE_IR_Strobe_Item",2],["ACE_splint",1],["ACE_elasticBandage",20],["IDA_BactaBandage",1],["kat_guedel",1],["kat_IV_16",1],["ACE_plasmaIV_500",1],["ACE_morphine",2],["ACE_epinephrine",1],["kat_chestSeal",1],["ItemAndroid",1],["WBK_HeadLampItem_Narrow",1],["ACE_EntrenchingTool",1],["ACE_Canteen",2],["ACE_MRE_ChickenHerbDumplings",2],["ACE_MRE_BeefStew",2],["aux187_DC17_mag",4,40],["JLTS_stun_mag_long",2,5],["IDA_grenade_Smoke_mag",5,1]]],["aux187_vest_grenade",[["187th_80RND_15S_Mag",6,80],["IDA_grenade_Penetrator_mag",1,1],["IDA_grenade_Detonator_mag",4,1]]],["3AS_B_CloneTrooper_Rocket_F",[["ACE_bodyBag",1],["aux187_SignalFlare_Blue",1,1],["aux187_SignalFlare_Green",1,1],["aux187_SignalFlare_Yellow",1,1],["JLTS_RPS6_mag",3,1],["JLTS_RPS6_HE_mag",1,1],["187th_80RND_15S_Mag",4,80]]],"aux187_P2_Base_Helmet","ls_imperial_chestRig",["ACE_Vector","","","",[],[],""],["ItemMap","","JLTS_clone_comlink","ItemCompass","ACE_Altimeter","Aux187_NVG_Chip"]]],

//-----Pilot-----//
["Pilot",[["Aux187_3as_DC15S","","","",["187th_80RND_15S_Mag",80],[],""],[],["IDA_DCFG","","","",["IDA_SmokeBlue_LauncherGrenade",1],[],""],["aux187_P2_Base_Uniform",[["ACE_CableTie",3],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["ACE_tourniquet",3],["ACE_EarPlugs",1],["ACE_IR_Strobe_Item",2],["ACE_splint",1],["ACE_elasticBandage",20],["IDA_BactaBandage",1],["kat_guedel",1],["kat_IV_16",1],["ACE_plasmaIV_500",1],["ACE_morphine",2],["ACE_epinephrine",1],["kat_chestSeal",1],["ItemAndroid",1],["WBK_HeadLampItem_Narrow",1],["ACE_EntrenchingTool",1],["ACE_Canteen",2],["ACE_MRE_BeefStew",2],["ACE_MRE_ChickenHerbDumplings",2],["IDA_grenade_Smoke_mag",5,1]]],["aux187_Vest_holster",[["187th_80RND_15S_Mag",6,80],["IDA_grenade_Penetrator_mag",1,1],["IDA_grenade_Detonator_mag",2,1]]],["Aux187_Chestrig_LR",[["ACE_bodyBag",1],["ACE_40mm_Flare_white",4,1],["aux187_SignalFlare_Green",1,1],["aux187_SignalFlare_Blue",4,1],["187th_80RND_15S_Mag",4,80]]],"187_Pilot_HelmetP2","",["IDA_Electrobinoculars_Rep","","","",["Laserbatteries",1],[],""],["ItemMap","","JLTS_clone_comlink","ItemCompass","ACE_Altimeter","Aux187_NVG_Chip_Pilot"]]],

//-----Rifleman-----//
["Rifleman",[["Aux187_3as_DC15S","","","",["187th_80RND_15S_Mag",80],[],""],[],["aux187_DC17","","","",["aux187_mag_80Rnd_pistol", 40],["JLTS_stun_mag_long",5],""],["aux187_P2_Base_Uniform",[["ACE_CableTie",3],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["ACE_tourniquet",3],["ACE_EarPlugs",1],["ACE_IR_Strobe_Item",2],["ACE_splint",1],["ACE_elasticBandage",20],["IDA_BactaBandage",1],["kat_guedel",1],["kat_IV_16",1],["ACE_plasmaIV_500",1],["ACE_morphine",2],["ACE_epinephrine",1],["kat_chestSeal",1],["ItemAndroid",1],["WBK_HeadLampItem_Narrow",1],["ACE_EntrenchingTool",1],["ACE_Canteen",2],["ACE_MRE_BeefStew",2],["ACE_MRE_ChickenHerbDumplings",2],["aux187_DC17_mag",4,40],["JLTS_stun_mag_long",2,5],["IDA_grenade_Smoke_mag",5,1]]],["aux187_vest_grenade",[["187th_80RND_15S_Mag",6,80],["IDA_grenade_Penetrator_mag",1,1],["IDA_grenade_Detonator_mag",4,1]]],["aux187_backpack_trooper_base",[["ACE_bodyBag",1],["aux187_SignalFlare_Blue",1,1],["aux187_SignalFlare_Green",1,1],["aux187_SignalFlare_Yellow",1,1],["187th_80RND_15S_Mag",4,80]]],"aux187_P2_Base_Helmet","ls_imperial_chestRig",["ls_clone_electrobinocularsCommander_night","","","",["Laserbatteries",1],[],""],["ItemMap","","JLTS_clone_comlink","ItemCompass","ACE_Altimeter","Aux187_NVG_Chip"]]],

//-----RTO-----//
["RTO",[["Aux187_3as_DC15S","","","",["187th_80RND_15S_Mag",80],[],""],[],["aux187_DC17","","","",["aux187_mag_80Rnd_pistol", 40],["JLTS_stun_mag_long",5],""],["aux187_P2_Base_Uniform",[["ACE_CableTie",3],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["ACE_tourniquet",3],["ACE_EarPlugs",1],["ACE_IR_Strobe_Item",2],["ACE_splint",1],["ACE_elasticBandage",20],["IDA_BactaBandage",1],["kat_guedel",1],["kat_IV_16",1],["ACE_plasmaIV_500",1],["ACE_morphine",2],["ACE_epinephrine",1],["kat_chestSeal",1],["ItemAndroid",1],["WBK_HeadLampItem_Narrow",1],["ACE_EntrenchingTool",1],["ACE_Canteen",2],["ACE_MRE_BeefStew",2],["ACE_MRE_ChickenHerbDumplings",2],["aux187_DC17_mag",4,40],["JLTS_stun_mag_long",2,5],["IDA_grenade_Smoke_mag",5,1]]],["aux187_vest_grenade",[["187th_80RND_15S_Mag",6,80],["IDA_grenade_Penetrator_mag",1,1],["IDA_grenade_Detonator_mag",4,1]]],["aux187_backpack_trooper_base",[["ACE_bodyBag",1],["aux187_SignalFlare_Blue",1,1],["aux187_SignalFlare_Green",1,1],["aux187_SignalFlare_Yellow",1,1],["187th_80RND_15S_Mag",4,80]]],"aux187_P2_Base_Helmet","ls_imperial_chestRig",["ls_clone_electrobinocularsCommander_night","","","",["Laserbatteries",1],[],""],["ItemMap","","JLTS_clone_comlink","ItemCompass","ACE_Altimeter","Aux187_NVG_Chip"]]],


//-----The Fucking New Guy-----//
["The Fucking New Guy",[["Aux187_3as_DC15S","","","",["187th_80RND_15S_Mag",80],[],""],[],["aux187_DC17","","","",["aux187_mag_80Rnd_pistol", 40],["JLTS_stun_mag_long",5],""],["187th_Clone_Recruit",[["ACE_CableTie",3],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["ACE_tourniquet",3],["ACE_EarPlugs",1],["ACE_IR_Strobe_Item",2],["ACE_splint",1],["ACE_elasticBandage",20],["IDA_BactaBandage",1],["kat_guedel",1],["kat_IV_16",1],["ACE_plasmaIV_500",1],["ACE_morphine",2],["ACE_epinephrine",1],["kat_chestSeal",1],["ItemAndroid",1],["WBK_HeadLampItem_Narrow",1],["ACE_EntrenchingTool",1],["ACE_Canteen",1],["ACE_MRE_BeefStew",1],["ACE_MRE_ChickenHerbDumplings",1],["aux187_DC17_mag",4,40],["JLTS_stun_mag_long",2,5],["3AS_SmokeWhite",5,1]]],["aux187_Vest_holster",[["187th_80RND_15S_Mag",6,80],["IDA_grenade_Detonator_mag",4,1],["IDA_grenade_Penetrator_mag",1,1]]],["187_Small_Backpack",[["ACE_bodyBag",1],["aux187_SignalFlare_Blue",1,1],["aux187_SignalFlare_Green",1,1],["aux187_SignalFlare_Yellow",1,1],["187th_80RND_15S_Mag",4,80]]],"187_Clone_Helmet_Recruit","ls_imperial_chestRig",["IDA_Electrobinoculars_Rep","","","",["Laserbatteries",1],[],""],["ItemMap","","JLTS_clone_comlink","ItemCompass","ACE_Altimeter","Aux187_NVG_Chip"]]],

//-----Z6-----//
["Z6",[["Aux187_Z6_IDA","","","",["187th_300RND_Z6_Mag",300],[],""],[],["aux187_DC17","","","",["aux187_mag_80Rnd_pistol", 40],["JLTS_stun_mag_long",5],""],["aux187_P2_Base_Uniform",[["ACE_CableTie",3],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["ACE_tourniquet",3],["ACE_EntrenchingTool",1],["ACE_EarPlugs",1],["ACE_bodyBag",1],["ACE_IR_Strobe_Item",2],["ACE_splint",1],["IDA_BactaBandage",1],["ACE_elasticBandage",20],["kat_IV_16",1],["kat_guedel",1],["ACE_plasmaIV_500",1],["ACE_morphine",2],["ACE_epinephrine",1],["kat_chestSeal",1],["ItemAndroid",1],["ACE_Canteen",2],["ACE_MRE_BeefStew",2],["ACE_MRE_ChickenHerbDumplings",2],["aux187_DC17_mag",4,40],["JLTS_stun_mag_long",2,5],["IDA_grenade_Smoke_mag",5,1]]],["aux187_Vest_holster",[["187th_300RND_Z6_Mag",3,300],["IDA_grenade_Penetrator_mag",1,1],["IDA_grenade_Detonator_mag",2,1]]],["aux187_backpack_trooper_base",[["ACE_Tripod",1],["aux187_SignalFlare_Blue",1,1],["aux187_SignalFlare_Green",1,1],["aux187_SignalFlare_Yellow",1,1]]],"aux187_P2_Base_Helmet","ls_imperial_chestRig",["IDA_Electrobinoculars_Rep","","","",["Laserbatteries",1],[],""],["ItemMap","","JLTS_clone_comlink","ItemCompass","ACE_Altimeter","Aux187_NVG_Chip"]]],

//-----Zeus-----//
["Zeus",[[],[],["aux187_DC17","","","",["aux187_mag_80Rnd_pistol", 40],["JLTS_stun_mag_long",5],""],["JMSLLTE_EmpOfficerCoat_green_F_CombatUniform",[["cigs_lucky_strike_cigpack",1,20],["cigs_matches",1,10]]],["JMSLLTE_Jinata_holster",[]],["Aux187_Chestrig_LR",[]],"JMSLLTE_OfcapP_br_helmet","cigs_lucky_strike_cig0",["ACE_Vector","","","",[],[],""],["ItemMap","","JLTS_clone_comlink","ItemCompass","ACE_Altimeter","fsob_Beard02_Dark_nvg"]]]

];

//----------LoadOuts End----------//

//-------add loadouts to ace default loadouts------
{[_x select 0,_x select 1] call ace_arsenal_fnc_addDefaultLoadout}forEach _allLoadOuts;
