        class aux187_CustomHelmet_Model
		{
			options[]=
			{
				"Customs"
			};
			label="[187th] Custom Helmets";
			class Customs
			{
				alwaysSelectable=1;
				changeingame=0;
				changedelay=0;
				label="Customs";
				values[]=
				{
					"Blade",
					"Boss",
					"Buzz",
					"Carmine",
					"Crypto",
					"Dross",
					"Dubz",
					"Fader",
					"Fish",
					"Fives",
					"Fluffy",
					"Hesh",
					"Horizon",
					"Ixi",
					"Iron",
					"Kalani",
					"Knight",
					"Kraken",
					"Lord",
					"Mindless",
					"Nexu",
					"Ouroboros",
					"Ringer",
					"Star",
					"Tac",
					"Ted",
					"Tim",
					"Un",
					"Vinokurov",
					"Scorch",
					"Jack",
					"Gandalf"
				};
            };
        };
