        class aux187_CustomUniform_Model
        {
            options[]=
            {
                "Customs"
            };
            label="[187th] Custom Uniforms";
            class Customs
            {
                alwaysSelectable=1;
                changeingame=0;
                changedelay=0;
                label="Customs";
                values[]=
                {
                    "Blade",
                    "Boss",
                    "Buzz",
                    "Crypto",
                    "Dross",
                    "Dubz",
                    "Fader",
                    "Hawk",
                    "Hesh",
                    "Horizon",
                    "Hunt",
                    "Iron",
                    "Isaac",
                    "Janitor",
                    "Kalani",
                    "Kraken",
                    "Lord",
                    "Mindless",
                    "Mixer",
                    "Multicam",
                    "Nexu",
                    "Ouroboros",
                    "Seek",
                    "Ringer",
                    "Solembum",
                    "Star",
                    "Tac",
                    "Tim",
                    "Toad",
                    "Un",
                    "Vinokurov",
                    "Revan",
                };
            };
        };
