        class aux187_CustomUniform_Model
        {
            options[]=
            {
                "Customs"
            };
            label="[187th] Custom Uniforms";
            class Customs
            {
                alwaysSelectable=1;
                changeingame=0;
                changedelay=0;
                label="Customs";
                values[]=
                {
                    "Boss",
                    "Crypto",
                    "Dubz",
                    "Fader",
                    "Hesh",
                    "Horizon",
                    "Iron",
                    "Janitor",
                    "Kalani",
                    "Kraken",
                    "Lord",
                    "Mindless",
                    "Multicam",
                    "Nexu",
                    "Ouroboros",
                    "Ringer",
                    "Star",
                    "Tac",
                    "Tim",
                    "Un",
                    "Vinokurov",
                    "Jack",
                    "Scorch",
                    "Fish"
                };
            };
        };
