name = "187th Legion Aux Mod"
author = "187th Legion"
prefix = "aux187"
mainprefix = "z"

[files]
include = [
    "mod.cpp",
    "meta.cpp",
    "LICENSE",
    "logo.paa",
]

[properties]
author = "187th Legion"
url = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"


[version]

major = 1
minor = 0
patch = 4
build = 3

git_hash = 0